-- MySQL Script generated by MySQL Workbench
-- Fri Dec 27 06:51:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sinapsis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sinapsis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sinapsis` DEFAULT CHARACTER SET utf8 ;
USE `sinapsis` ;

-- -----------------------------------------------------
-- Table `sinapsis`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinapsis`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinapsis`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinapsis`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `usuario` VARCHAR(30) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_cliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `sinapsis`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinapsis`.`campania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinapsis`.`campania` (
  `idCampania` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `idUsuario` INT NOT NULL,
  `fechaHoraProgramacion` DATETIME NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idCampania`),
  INDEX `fk_campania_usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_campania_usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sinapsis`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinapsis`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinapsis`.`mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `idCampania` INT NOT NULL,
  `estadoEnvio` TINYINT(1) NOT NULL,
  `fechaHoraEnvio` DATETIME NOT NULL,
  `mensaje` VARCHAR(160) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idMensaje`),
  INDEX `fk_mensaje_campania1_idx` (`idCampania` ASC) VISIBLE,
  CONSTRAINT `fk_mensaje_campania1`
    FOREIGN KEY (`idCampania`)
    REFERENCES `sinapsis`.`campania` (`idCampania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DELIMITER $$

CREATE PROCEDURE `sp_listar_mensajes_activos`(
    IN `p_mes` INT,
    IN `p_cliente_id` INT NULL
)
BEGIN
    SELECT 
        m.idMensaje, 
        m.idCampania, 
        m.estadoEnvio, 
        m.fechaHoraEnvio, 
        m.mensaje, 
        m.estado,
        c.nombre AS cliente_nombre
    FROM 
        sinapsis.mensaje m
    JOIN 
        sinapsis.campania ca ON m.idCampania = ca.idCampania
    JOIN 
        sinapsis.usuario u ON ca.idUsuario = u.idUsuario
    JOIN 
        sinapsis.cliente c ON u.idCliente = c.idCliente
    WHERE 
        m.estado = 1 
        AND MONTH(m.fechaHoraEnvio) = p_mes
        AND (p_cliente_id IS NULL OR u.idCliente = p_cliente_id)
    ORDER BY 
        m.fechaHoraEnvio DESC;
END $$


CREATE PROCEDURE `sp_agregar_campania_por_cliente`(
    IN `p_cliente_id` INT,
    IN `p_nombre_campania` VARCHAR(200),
    IN `p_fechaHoraProgramacion` DATETIME,
    IN `p_estado` TINYINT
)
BEGIN
    DECLARE v_idUsuario INT;

    SELECT idUsuario INTO v_idUsuario
    FROM sinapsis.usuario
    WHERE idCliente = p_cliente_id
    LIMIT 1;

    IF v_idUsuario IS NULL THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'No se encontró un usuario asociado al cliente especificado.';
    ELSE
        INSERT INTO sinapsis.campania (nombre, idUsuario, fechaHoraProgramacion, estado)
        VALUES (p_nombre_campania, v_idUsuario, p_fechaHoraProgramacion, p_estado);
    END IF;

END $$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
